# Copyright 2024 Moval Agroingeniería
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html)

from __future__ import annotations

from typing import Optional, Union

from psycopg2 import sql

from odoo import SUPERUSER_ID, _, api
from odoo.exceptions import ValidationError
from odoo.sql_db import BaseCursor

EnvOrCr = Union[api.Environment, BaseCursor]

POSTGIS_EXT = "postgis"

GIS_SCHEMA = "public"
PARCEL_TABLE = "ter_gis_parcel"
PROPERTY_TABLE = "ter_gis_property"
PARCEL_VIEW = "ter_gis_parcel_model"

PARAM_PREFIX = "base_ter."
PARAM_DEFAULTS = {
    f"{PARAM_PREFIX}area_unit_is_ha": True,
    f"{PARAM_PREFIX}area_unit_name": "ha",
    f"{PARAM_PREFIX}area_unit_value_in_ha": 1,
    f"{PARAM_PREFIX}warning_diff_areas": 10,
    f"{PARAM_PREFIX}same_parcelmanager_propertyowner": False,
    f"{PARAM_PREFIX}aerial_image_wmsbase_url": "https://www.ign.es/wms-inspire/pnoa-ma",
    f"{PARAM_PREFIX}aerial_image_wmsbase_layers": "OI.OrthoimageCoverage",
    f"{PARAM_PREFIX}aerial_image_wmsvec_url": "https://gis.moval.es/wms/my_client",
    f"{PARAM_PREFIX}aerial_image_wmsvec_parcel_name": "parcel_perimeter",
    f"{PARAM_PREFIX}aerial_image_wmsvec_parcel_filter": True,
    f"{PARAM_PREFIX}aerial_image_wmsvec_property_name": "property_perimeter",
    f"{PARAM_PREFIX}aerial_image_wmsvec_property_filter": True,
    f"{PARAM_PREFIX}aerial_image_height": 512,
    f"{PARAM_PREFIX}aerial_image_zoom": 1.2,
    f"{PARAM_PREFIX}gis_viewer_url": "https://gis.moval.es/my_client/visor",
    f"{PARAM_PREFIX}gis_viewer_username": "tecnico",
    f"{PARAM_PREFIX}gis_viewer_password": "my_password",
    f"{PARAM_PREFIX}gis_viewer_epsg": 25830,
    f"{PARAM_PREFIX}gis_viewer_previs_additional_args": "mode=min",
}


def _env(env_or_cr: EnvOrCr) -> api.Environment:
    if isinstance(env_or_cr, api.Environment):
        return env_or_cr
    if isinstance(env_or_cr, BaseCursor):
        return api.Environment(env_or_cr, SUPERUSER_ID, {})
    raise TypeError(f"Unsupported hook argument type: {type(env_or_cr)!r}")


def _ensure_postgis(env: api.Environment) -> None:
    # Best-effort create extension: may fail if DB user lacks privileges.
    try:
        env.cr.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    except Exception:
        env.cr.rollback()

    env.cr.execute(
        "SELECT EXISTS(SELECT 1 FROM pg_extension WHERE extname = %s)", (POSTGIS_EXT,)
    )
    if not env.cr.fetchone()[0]:
        raise ValidationError(
            _(
                "PostGIS is not installed or cannot be enabled in this database. "
                "Please ask your administrator to install/enable PostGIS before installing this module."
            )
        )


def _set_db_search_path(env: api.Environment) -> None:
    # Keep it explicit and safe.
    env.cr.execute(
        sql.SQL("ALTER DATABASE {} SET search_path = public, postgis").format(
            sql.Identifier(env.cr.dbname)
        )
    )


def _create_gis_structures(env: api.Environment) -> None:
    # NOTE: Use "geometry" type directly (from PostGIS), avoid schema-qualified "postgis.geometry".
    env.cr.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {GIS_SCHEMA}.{PARCEL_TABLE} (
            gid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(255) NOT NULL UNIQUE CHECK (name <> ''),
            geom geometry(MultiPolygon, 25830)
        )
        """
    )
    env.cr.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {PARCEL_TABLE}_geom_gist
            ON {GIS_SCHEMA}.{PARCEL_TABLE}
            USING gist (geom)
        """
    )

    # Keep "gid" externally managed if that is your contract with GIS source.
    env.cr.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {GIS_SCHEMA}.{PROPERTY_TABLE} (
            gid INTEGER NOT NULL,
            name VARCHAR(255) NOT NULL UNIQUE CHECK (name <> ''),
            geom geometry(MultiPolygon, 25830),
            CONSTRAINT {PROPERTY_TABLE}_pkey PRIMARY KEY (gid)
        )
        """
    )
    env.cr.execute(
        f"""
        CREATE INDEX IF NOT EXISTS {PROPERTY_TABLE}_geom_gist
            ON {GIS_SCHEMA}.{PROPERTY_TABLE}
            USING gist (geom)
        """
    )

    # Deterministic id: stable across refreshes.
    env.cr.execute(
        f"""
        CREATE OR REPLACE VIEW {PARCEL_VIEW} AS (
            SELECT
                row_number() OVER (ORDER BY tgp.name) AS id,
                tgp.name,
                ST_AsGeoJSON(tgp.geom) AS geom_geojson,
                tp.id AS parcel_id,
                tp.partner_id AS partner_id,
                tp.active AS is_active
            FROM {GIS_SCHEMA}.{PARCEL_TABLE} tgp
            LEFT JOIN ter_parcel tp ON tgp.name = tp.name
        )
        """
    )


def _init_params(env: api.Environment) -> None:
    params = env["ir.config_parameter"].sudo()
    for key, value in PARAM_DEFAULTS.items():
        params.set_param(key, value)


def pre_init_hook(env_or_cr: EnvOrCr) -> None:
    env = _env(env_or_cr)
    _ensure_postgis(env)
    _set_db_search_path(env)


def post_init_hook(env_or_cr: EnvOrCr, registry: Optional[object] = None) -> None:
    env = _env(env_or_cr)

    _create_gis_structures(env)
    _init_params(env)

    # Load i18n_extra.
    env.ref("base.module_base_ter")._update_translations(overwrite=True)


def uninstall_hook(env_or_cr: EnvOrCr, registry: Optional[object] = None) -> None:
    env = _env(env_or_cr)

    env.cr.execute(f"DROP VIEW IF EXISTS {PARCEL_VIEW}")
    env.cr.execute(f"DROP TABLE IF EXISTS {GIS_SCHEMA}.{PARCEL_TABLE}")
    env.cr.execute(f"DROP TABLE IF EXISTS {GIS_SCHEMA}.{PROPERTY_TABLE}")

    with env.cr.savepoint():
        env.cr.execute(
            "DELETE FROM ir_config_parameter WHERE key LIKE %s", (f"{PARAM_PREFIX}%",)
        )
