# Copyright 2026 Moval Agroingeniería S.L.
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html)
# pylint: disable=line-too-long,protected-access

from __future__ import annotations

import json
from pathlib import Path
from typing import Optional

from odoo import api
from odoo.exceptions import ValidationError
from psycopg2 import sql

POSTGIS_EXT = "postgis"
POSTGIS_SCHEMA = "postgis"

GIS_SCHEMA = "public"
PARCEL_TABLE = "ter_gis_parcel"
PROPERTY_TABLE = "ter_gis_property"
UNIT_TABLE = "ter_gis_unit"
PARCEL_VIEW = "ter_gis_parcel_model"

PARAM_PREFIX = "base_ter."
PARAM_DEFAULTS = {
    f"{PARAM_PREFIX}area_unit_is_ha": True,
    f"{PARAM_PREFIX}area_unit_name": "ha",
    f"{PARAM_PREFIX}area_unit_value_in_ha": 1,
    f"{PARAM_PREFIX}warning_diff_areas": 10,
    f"{PARAM_PREFIX}same_parcelmanager_propertyowner": False,
    f"{PARAM_PREFIX}aerial_image_wmsbase_url": "https://www.ign.es/wms-inspire/pnoa-ma",
    f"{PARAM_PREFIX}aerial_image_wmsbase_layers": "OI.OrthoimageCoverage",
    f"{PARAM_PREFIX}aerial_image_wmsvec_url": "https://gis.moval.es/wms/my_client",
    f"{PARAM_PREFIX}aerial_image_wmsvec_parcel_name": "parcel_perimeter",
    f"{PARAM_PREFIX}aerial_image_wmsvec_parcel_filter": True,
    f"{PARAM_PREFIX}aerial_image_wmsvec_property_name": "property_perimeter",
    f"{PARAM_PREFIX}aerial_image_wmsvec_property_filter": True,
    f"{PARAM_PREFIX}aerial_image_height": 512,
    f"{PARAM_PREFIX}aerial_image_zoom": 1.2,
    # Change these defaults in production (Settings > Territory)
    f"{PARAM_PREFIX}gis_viewer_url": "https://gis.moval.es/my_client/visor",
    f"{PARAM_PREFIX}gis_viewer_username": "tecnico",
    f"{PARAM_PREFIX}gis_viewer_password": "my_password",
    f"{PARAM_PREFIX}gis_viewer_epsg": 25830,
    f"{PARAM_PREFIX}gis_viewer_previs_additional_args": "mode=min",
}


def _postgis_extension_exists(env: api.Environment) -> bool:
    env.cr.execute(
        "SELECT EXISTS(SELECT 1 FROM pg_extension WHERE extname = %s)",
        (POSTGIS_EXT,),
    )
    return bool(env.cr.fetchone()[0])


def _geometry_type_exists_any_schema(env: api.Environment) -> bool:
    env.cr.execute("SELECT EXISTS(SELECT 1 FROM pg_type WHERE typname = 'geometry')")
    return bool(env.cr.fetchone()[0])


def _set_search_path(env: api.Environment) -> None:
    env.cr.execute(
        sql.SQL("ALTER DATABASE {} SET search_path = public, {}").format(
            sql.Identifier(env.cr.dbname),
            sql.Identifier(POSTGIS_SCHEMA),
        )
    )
    env.cr.execute(
        sql.SQL("SET search_path TO public, {}").format(sql.Identifier(POSTGIS_SCHEMA))
    )


def _grant_postgis_privileges(env: api.Environment) -> None:
    env.cr.execute(
        sql.SQL("GRANT USAGE ON SCHEMA {} TO public").format(
            sql.Identifier(POSTGIS_SCHEMA)
        )
    )
    env.cr.execute(
        sql.SQL(
            "GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA {} TO public"
        ).format(sql.Identifier(POSTGIS_SCHEMA))
    )
    env.cr.execute(
        sql.SQL("GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA {} TO public").format(
            sql.Identifier(POSTGIS_SCHEMA)
        )
    )


def _ensure_postgis(env: api.Environment) -> None:
    try:
        env.cr.execute(
            sql.SQL("CREATE SCHEMA IF NOT EXISTS {}").format(
                sql.Identifier(POSTGIS_SCHEMA)
            )
        )
        env.cr.execute(
            sql.SQL("CREATE EXTENSION IF NOT EXISTS {}").format(
                sql.Identifier(POSTGIS_EXT)
            )
        )
        env.cr.execute(
            sql.SQL("ALTER EXTENSION {} SET SCHEMA {}").format(
                sql.Identifier(POSTGIS_EXT),
                sql.Identifier(POSTGIS_SCHEMA),
            )
        )
        _set_search_path(env)
        _grant_postgis_privileges(env)
    except Exception as exc:
        raise ValidationError(
            env._(
                "PostGIS could not be enabled in this database. "
                "Install PostGIS on PostgreSQL and ensure the DB user can run "
                "CREATE EXTENSION."
            )
        ) from exc

    if not _postgis_extension_exists(env) or not _geometry_type_exists_any_schema(env):
        raise ValidationError(
            env._(
                "PostGIS is not available in this database. "
                "Install/enable PostGIS and retry."
            )
        )


def _create_gis_structures(env: api.Environment) -> None:
    _set_search_path(env)

    env.cr.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.{}
            (
                gid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL UNIQUE CHECK (name <> ''),
                geom geometry(MultiPolygon, 25830)
            )
            """
        ).format(sql.Identifier(GIS_SCHEMA), sql.Identifier(PARCEL_TABLE))
    )
    env.cr.execute(
        sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {}.{} USING gist (geom)").format(
            sql.Identifier(f"{PARCEL_TABLE}_geom_gist"),
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(PARCEL_TABLE),
        )
    )

    env.cr.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.{}
            (
                gid INTEGER NOT NULL,
                name VARCHAR(255) NOT NULL UNIQUE CHECK (name <> ''),
                geom geometry(MultiPolygon, 25830),
                CONSTRAINT {} PRIMARY KEY (gid)
            )
            """
        ).format(
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(PROPERTY_TABLE),
            sql.Identifier(f"{PROPERTY_TABLE}_pkey"),
        )
    )
    env.cr.execute(
        sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {}.{} USING gist (geom)").format(
            sql.Identifier(f"{PROPERTY_TABLE}_geom_gist"),
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(PROPERTY_TABLE),
        )
    )

    env.cr.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.{}
            (
                gid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                unit_id INTEGER NOT NULL UNIQUE
                REFERENCES ter_unit(id) ON DELETE CASCADE,
                geom geometry(MultiPolygon, 25830)
            )
            """
        ).format(sql.Identifier(GIS_SCHEMA), sql.Identifier(UNIT_TABLE))
    )
    env.cr.execute(
        sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {}.{} USING gist (geom)").format(
            sql.Identifier(f"{UNIT_TABLE}_geom_gist"),
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(UNIT_TABLE),
        )
    )

    env.cr.execute(
        sql.SQL(
            """
            CREATE OR REPLACE VIEW {} AS (
                SELECT
                    row_number() OVER (ORDER BY tgp.name) AS id,
                    tgp.name,
                    ST_AsGeoJSON(tgp.geom) AS geom_geojson,
                    tp.id AS parcel_id,
                    tp.partner_id AS partner_id,
                    tp.active AS is_active,

                    -- log_access fields required by Odoo when _log_access=True
                    NULL::integer AS create_uid,
                    NOW() AT TIME ZONE 'UTC' AS create_date,
                    NULL::integer AS write_uid,
                    NOW() AT TIME ZONE 'UTC' AS write_date
                FROM {}.{} tgp
                LEFT JOIN ter_parcel tp ON tgp.name = tp.name
            )
            """
        ).format(
            sql.Identifier(PARCEL_VIEW),
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(PARCEL_TABLE),
        )
    )


def _ensure_gis_unit_table(env: api.Environment) -> None:
    """Create ter_gis_unit table if missing (e.g. after restore or partial init)."""
    _set_search_path(env)
    env.cr.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.{}
            (
                gid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                unit_id INTEGER NOT NULL UNIQUE
                REFERENCES ter_unit(id) ON DELETE CASCADE,
                geom geometry(MultiPolygon, 25830)
            )
            """
        ).format(sql.Identifier(GIS_SCHEMA), sql.Identifier(UNIT_TABLE))
    )
    env.cr.execute(
        sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {}.{} USING gist (geom)").format(
            sql.Identifier(f"{UNIT_TABLE}_geom_gist"),
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(UNIT_TABLE),
        )
    )


def _init_params(env: api.Environment) -> None:
    params = env["ir.config_parameter"].sudo()
    for key, value in PARAM_DEFAULTS.items():
        params.set_param(key, value)


def pre_init_hook(env: api.Environment) -> None:
    _ensure_postgis(env)


def _ensure_ter_unit_sequences(env: api.Environment) -> None:
    """Create default ter.use_unit sequence for each company that lacks one."""
    env["res.company"].search([])._get_or_create_ter_unit_sequence()


def _migrate_ter_unit_parcel_ids(env: api.Environment) -> None:
    """Populate parcel_ids from parcel_id for existing ter.use_unit records."""
    env.cr.execute(
        """
        INSERT INTO ter_unit_parcel_rel (unit_id, parcel_id)
        SELECT u.id, u.parcel_id
        FROM ter_unit u
        WHERE u.parcel_id IS NOT NULL
        AND NOT EXISTS (
            SELECT 1 FROM ter_unit_parcel_rel r
            WHERE r.unit_id = u.id AND r.parcel_id = u.parcel_id
        )
        """
    )


def _load_attribute_translations_es(env: api.Environment) -> None:
    """Load es_ES translations for ter.use_type.attribute and .value name fields."""
    path = Path(__file__).resolve().parent / "data" / "attribute_translations_es.json"
    if not path.exists():
        return
    with open(path, encoding="utf-8") as f:
        translations = json.load(f)
    for xmlid, es_value in translations.items():
        try:
            record = env.ref(xmlid, raise_if_not_found=False)
            if record and record._name in (
                "ter.use_type.attribute",
                "ter.use_type.attribute.value",
            ):
                record.sudo().update_field_translations("name", {"es_ES": es_value})
        except Exception:
            continue


def post_init_hook(env: api.Environment, _registry: Optional[object] = None) -> None:
    _ensure_postgis(env)
    _create_gis_structures(env)
    _init_params(env)
    _ensure_ter_unit_sequences(env)
    _migrate_ter_unit_parcel_ids(env)
    env.ref("base.module_base_ter")._update_translations(overwrite=True)
    _load_attribute_translations_es(env)


def uninstall_hook(env: api.Environment, _registry: Optional[object] = None) -> None:
    env.cr.execute(
        sql.SQL("DROP VIEW IF EXISTS {}").format(sql.Identifier(PARCEL_VIEW))
    )
    env.cr.execute(
        sql.SQL("DROP TABLE IF EXISTS {}.{}").format(
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(UNIT_TABLE),
        )
    )
    env.cr.execute(
        sql.SQL("DROP TABLE IF EXISTS {}.{}").format(
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(PARCEL_TABLE),
        )
    )
    env.cr.execute(
        sql.SQL("DROP TABLE IF EXISTS {}.{}").format(
            sql.Identifier(GIS_SCHEMA),
            sql.Identifier(PROPERTY_TABLE),
        )
    )

    with env.cr.savepoint():
        env.cr.execute(
            "DELETE FROM ir_config_parameter WHERE key LIKE %s",
            (f"{PARAM_PREFIX}%",),
        )
