# 2026 Moval Agroingeniería
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html)

{
    "name": "Territory Analytic - Geofolia Import",
    "version": "18.0.1.2.0",
    "category": "Territory Management",
    "summary": "Geofolia JSON import: FSM + Territory (1 location = 1 use unit)",
    "license": "AGPL-3",
    "website": "https://www.moval.es",
    "author": "Moval",
    "depends": [
        "base",
        "base_ter",
        "base_ter_analytic",
        "fieldservice",
        "fieldservice_activity",
        "fieldservice_account",
        "fieldservice_vehicle",
        "fieldservice_timesheet",
        "account",
        "analytic",
        "hr",
        "product",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/ter_analytic_geofolia_menus.xml",
        "views/res_config_settings_views.xml",
        "views/geofolia_import_job_views.xml",
        "views/geofolia_import_line_views.xml",
        "views/geofolia_import_product_line_views.xml",
        "views/geofolia_import_employee_line_views.xml",
        "views/geofolia_import_partner_line_views.xml",
        "views/geofolia_import_harvested_product_line_views.xml",
        "views/geofolia_import_equipment_line_views.xml",
        "views/geofolia_import_activity_line_views.xml",
        "views/geofolia_import_activity_employee_line_views.xml",
        "wizards/import_wizard_views.xml",
        "views/account_analytic_line_views.xml",
        "views/fsm_equipment_views.xml",
        "views/fsm_location_views.xml",
        "views/fsm_person_views.xml",
        "views/hr_employee_views.xml",
        "views/product_product_views.xml",
        "views/res_partner_views.xml",
        "views/ter_parcel_views.xml",
        "views/ter_use_unit_views.xml",
        "views/timesheets_analysis_report_views.xml",
        "views/fsm_order_product_usage_views.xml",
        "views/fsm_order_equipment_usage_views.xml",
        "views/fsm_order_person_usage_views.xml",
        "views/fsm_order_views.xml",
    ],
    "post_init_hook": "post_init_hook",
}
