# 2026 Moval Agroingenieria
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html)

from odoo import api
from odoo.exceptions import ValidationError
from psycopg2 import sql

POSTGIS_EXT = "postgis"


def _ensure_postgis(env: api.Environment) -> None:
    try:
        env.cr.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    except Exception as exc:
        raise ValidationError(
            env._(
                "PostGIS could not be enabled in this database. "
                "Install PostGIS on PostgreSQL and ensure the DB user can run "
                "CREATE EXTENSION."
            )
        ) from exc

    env.cr.execute(
        "SELECT EXISTS(SELECT 1 FROM pg_extension WHERE extname = %s)",
        (POSTGIS_EXT,),
    )
    if not env.cr.fetchone()[0]:
        raise ValidationError(
            env._(
                "PostGIS is not available in this database. "
                "Install/enable PostGIS and retry."
            )
        )


def _create_point_gis_table(env: api.Environment) -> None:
    env.cr.execute(
        sql.SQL(
            """
            CREATE TABLE IF NOT EXISTS {}.{}
            (
                gid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255) NOT NULL UNIQUE CHECK (name <> ''),
                geom geometry(Point, 25830)
            )
            """
        ).format(
            sql.Identifier("public"),
            sql.Identifier("point_gis_point"),
        )
    )
    env.cr.execute(
        sql.SQL("CREATE INDEX IF NOT EXISTS {} ON {}.{} USING gist (geom)").format(
            sql.Identifier("point_gis_point_geom_gist"),
            sql.Identifier("public"),
            sql.Identifier("point_gis_point"),
        )
    )


def post_init_hook(env: api.Environment) -> None:
    _ensure_postgis(env)
    _create_point_gis_table(env)
