{
    "name": "Geofolia JSON Import",
    "version": "18.0.2.0.0",
    "category": "Tools",
    "summary": "JSON importer for Geofolia (Fields / Products / Maintenance)",
    "license": "LGPL-3",
    "website": "https://www.moval.es",
    "author": "Moval Agroingeniería S.L.",
    "depends": [
        "base",
        "account",
        "analytic",
        "hr",
        "hr_timesheet",
        "product",
        "project",
        "base_ter",
        "base_maintenance",
        "maintenance_project",
        "maintenance_timesheet",
        "maintenance_product",
        "maintenance_request_employee",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/geofolia_menus.xml",
        "views/geofolia_reports.xml",
        "views/import_job_list.xml",
        "views/import_job_form.xml",
        "views/import_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/account_analytic_line_views.xml",
        "views/maintenance_equipment_views.xml",
        "views/maintenance_request_views.xml",
        "views/ter_unit_views.xml",
        "views/ter_parcel_views.xml",
        "views/res_partner_views.xml",
        "views/product_product_views.xml",
        "views/project_task_views.xml",
        "views/hr_employee_views.xml",
    ],
}
