{
    "name": "Geofolia JSON Import",
    "version": "18.0.1.0.1",
    "category": "Tools",
    "summary": "JSON importer for Geofolia (Fields / Products)",
    "license": "LGPL-3",
    "website": "https://www.moval.es",
    "author": "Moval Agroingeniería",
    "depends": ["base",
                "account",
                "analytic",
                "hr",
                "hr_timesheet",
                "product",
                "project",
                "base_ter"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/geofolia_menus.xml",
        "views/import_job_list.xml",
        "views/import_job_form.xml",
        "views/import_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "views/account_analytic_line_views.xml",
        "views/ter_unit_views.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
}
