{
    "name": "Geofolia JSON Import (Pro)",
    "version": "18.0.1.0.0",
    "category": "Tools",
    "summary": "Importador JSON para Geofolia (Fields / Products)",
    "license": "LGPL-3",
    "website": "https://www.moval.es",
    "author": "Moval Agroingeniería",
    "depends": ["base",
                "account",
                "analytic",
                "hr",
                "product",
                "base_ter"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "views/import_job_views.xml",
        "views/import_wizard_views.xml",
    ],
    "demo": [],
    "installable": True,
    "application": False,
}
